In [1]:
import pandas as pd

In [25]:
data = "cities.csv"
cities_df = pd.read_csv(data)
cities = cities_df.dropna()
cities

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,Cape Town,0,ZA,1589156682,93,-33.93,18.42,288.71,4.10
1,1,Yulara,93,AU,1589156806,35,-25.24,130.99,287.15,7.70
2,2,Mumford,100,GH,1589156806,77,5.26,-0.76,299.37,4.68
3,3,Kutum,0,SD,1589156807,23,14.20,24.67,292.92,3.13
4,4,Khatanga,93,RU,1589156807,98,71.97,102.50,271.56,2.73
...,...,...,...,...,...,...,...,...,...,...
533,533,Skjervøy,98,NO,1589156877,82,70.03,20.97,274.73,4.58
534,534,Shangzhi,76,CN,1589156877,63,45.22,127.97,284.87,5.68
535,535,Pital,78,CO,1589156877,82,2.27,-75.80,294.64,2.46
536,536,Douentza,51,ML,1589156877,35,15.00,-2.95,304.10,2.82
537,537,Española,1,US,1589156877,18,35.99,-106.08,296.48,3.60

In [34]:
output_location = "cities.html"
cities.to_html(output_location, header=True, index=True, formatters="utf-8", decimal='.', get=)
# c=cities.to_html("cities.html")

AttributeError: 'str' object has no attribute 'get'

In [32]:
data.appendrow(data,2,3,4,5)

AttributeError: 'str' object has no attribute 'appendrow'